Feature/transaction detail view
twttr/zmoney pull request #4
Opened 2021-05-09 18:10 UTC by twttr

- add transaction detail view
- fix main thread issues

2021-05-10 13:27 UTC, gregoryvit requested changes
Архитектурно и структурно все ок. Внес несколько комментариев и еще у меня проблемы с моим аккаунтом вылезли, прикладываю мой `json`, там нужно в моделях и декодер внести правки
[diff_response_0.json.zip](https://github.com/twttr/zmoney/files/6452347/diff_response_0.json.zip)

2021-05-10 13:27 UTC, gregoryvit commented on zmoney/Controllers/TransactionsViewController.swift
> +                    Zservice.shared.logout()
Давай так не будем делать, так как ошибка на запрос – не повод делать разлогин :)

2021-05-10 13:27 UTC, gregoryvit commented on zmoney/Models/TransactionCell/TransactionCellModel.swift
> +        }
```suggestion
        categories = transaction.categories?.map { $0.title } ?? []
```

2021-05-10 13:31 UTC, twttr commented on zmoney/Controllers/TransactionsViewController.swift
> +                    Zservice.shared.logout()
Я так сделал потому что мне 401 прилетела разок и в таком случае юзеру придется перелогиниваться. Есть какой-то лучше вариант?

2021-05-16 14:04 UTC, gregoryvit requested changes
Неплохо со стейтами получилось, но нужно там пару моментов поправить

2021-05-16 14:04 UTC, gregoryvit commented on zmoney/Models/TransactionCell/TransactionCellModel.swift
> +        categories = transaction.categories?.reduce(into: [String]()) {
Не очень кейс для использования `reduce`. Здесь целесообразнее использовать `map`.
Не первый раз с `map`, `reduce`, `filter`, ... возникают проблемки. Почитай про них поподробнее. Например здесь расписано вроде неплохо https://gist.github.com/SheldonWangRJT/791c85749051cf4b63b1590f08143156

2021-05-16 14:04 UTC, gregoryvit commented on zmoney/Models/Network/DiffResponseModel.swift
> +        tag = try container.decode([Tag].self, forKey: .tag).reduce(into: [String: Tag]()) {
Здесь `reduce` к месту используется 👍

2021-05-16 14:04 UTC, gregoryvit commented on zmoney/Models/Network/DiffResponseModel.swift
>              if let categoriesStrings = transactions[index].tag {
Вот это какая-то очень сложная конструкция, попробуй упростить

2021-05-21 06:44 UTC, gregoryvit requested changes
Есть несколько критичных моментов, которые нужно поправить в логике работы стейт-менеджера

2021-05-21 06:44 UTC, gregoryvit commented on zmoney/Models/StateManager.swift
> +        errorView.isHidden = false
Здесь нужен `true`
```suggestion
        errorView.isHidden = true
```

2021-05-21 06:44 UTC, gregoryvit commented on zmoney/Models/StateManager.swift
> +struct StateManager: StateHolder, StateApplicable {
Если дернуть PullToRefresh, то что-то происходит с `frame` у `LoadingView`. Нужно поправить
![Simulator Screen Shot - iPhone 12 - 2021-05-21 at 09 26 24](https://user-images.githubusercontent.com/3230886/119092075-a4b05b00-ba16-11eb-8fe9-1ee1832ddb1a.png)

2021-05-21 06:44 UTC, gregoryvit commented on zmoney/Controllers/TransactionsViewController.swift
> +        self.stateController?.state = .loading
Интересный момент. Если дернуть PullToRefresh, то у нас начинает отображаться `RefreshControl`, потом мы весь экран накрываем `LoadingView` из-за чего выглядит довольно дёргано при использовании.

`RefreshControl` подразумевает, то что у нас уже что-то отображается на экране и мы хотим это обновить без блокирования всего интерфейса. См. приложение почты например, нам не нужно ждать окончания загрузки зачастую, мы просто дернули PTR и пошли смотреть непрочитанные письма и ожидаем, что когда вернемся, то все обновится.

Блокирующий лоадер лучше использовать в случаях, когда действия пользователя могут что-то сломать. Например, при оплате товаров через ApplePay, после подтверждения намерения оплатить с помощью биометрии, происходит блокирующая загрузка: кнопка cancel становится не активной, а модальное окно никак не скрыть. Как раз из-за того, что нужно сохранить фокус внимания пользователя на процессе оплаты и не дать ему возможности как-то уйти с этого экрана случайно.

Дополнительно отмечу, что сейчас, если мы захотим добавить логику обновления в фоне какую-нибудь. Например, чтобы по таймеру происходило обновление транзакций и список обновлялся, то вместо того, чтобы тихонько все обновить и сообщить пользователю, что перед ним актуальные данные, мы явно заблочим экран загрузчиком :)

В случае с экраном транзакций, нам не критично, что пользователь будет скролить экран и будет по приложению гулять, поэтому предлагаю оставить PTR и не показывать блокирующую загрузку при обновлении контента, но показывать при начальной загрузке контента.

2021-05-21 22:45 UTC, gregoryvit requested changes

2021-05-21 22:45 UTC, gregoryvit commented on zmoney/Models/StateManager.swift
> +        view.frame = loadedView.frame
Здесь не очень брать `frame` у дочерней `view`, так как он запросто может поменяться. Лучше здесь завязывать `frame` вьюшек со стейтом на корневую `view`.

```suggestion
        view.frame = rootView.bounds
```

2021-05-21 22:45 UTC, gregoryvit commented on zmoney/Controllers/TransactionsViewController.swift
> +        if firstTimeLoad() {
Что-то сильно усложнил здесь. Смотри, чтобы чекнуть, что загрузка прошла первый раз мы можем либо проверять, что у нас пустой массив `transactionsModels`, либо, что у нас текущий стейт `noData`.

2021-05-22 04:27 UTC, twttr commented on zmoney/Controllers/TransactionsViewController.swift
> +        if firstTimeLoad() {
а, я чето решил что совсем в первый раз

2021-05-22 04:47 UTC, twttr commented on zmoney/Controllers/TransactionsViewController.swift
> +        }
вот этот кусочек мне не очень нравится, но как альтернативу я придумал только
`state = state == .noData ? .loading : .noData`

2021-05-26 23:12 UTC, gregoryvit requested changes
`state` и `.noData` давай попробуем вынести в `StateManager` и если лучше будет, то сольем

2021-05-28 22:00 UTC, gregoryvit requested changes
Нужно упростить немного реализацию

2021-05-28 22:00 UTC, gregoryvit commented on zmoney/Models/StateManager.swift
>          }
Немного перемудрил :) 
Почитай про Property observers в Swift https://docs.swift.org/swift-book/LanguageGuide/Properties.html#ID262
В данном случае неплохо подойдет `willSet`, тогда можно сделать так
```suggestion
        willSet {
            self.apply(state: newValue)
        }
```

В таком случае, не нужно свойство `currentState`, так как текущий стейт можно брать из свойства `state`

2021-05-28 22:31 UTC, twttr commented on zmoney/Models/StateManager.swift
> +            guard self.state == .noData else { return }
тут оно и без self работает конечно, но я оставил для читабельности

2021-05-29 15:55 UTC, twttr commented on zmoney/Models/ApplicationCoordinator.swift
> +protocol ApplicationCoordinatorDelegate: AnyObject {
Так как viewWillAppear дергается при переходах, но не при скрытии модального окна - с ним я не сомг сделать, в итоге решил через делегата от ApplicationCoordinator. Так оно работает в точности как нужно.

2021-06-04 23:21 UTC, gregoryvit requested changes
Лучше сделать все же через NotificationCenter. Не забудь добавить `post` в методы изменения и удаления токена.

2021-06-04 23:21 UTC, gregoryvit commented on zmoney/Controllers/TransactionsViewController.swift
> +
Решение через делегата в координаторе переуплотняет сильно схему. И если, к примеру, нам нужно будет в каком-то другом месте приложения отслеживать статус авторизации (в кнопке какой-нибудь), то придется ее связывать с ApplicationCoordinator.delegate, а делегат только один может быть и т.п.

Здесь лучше использование паттерна Observer подойдет. И я предлагаю сделать оповещения через NotificationCenter. Будет тогда как-то так

```suggestion
NotificationCenter.default.addObserver(forName: .zMoneyConfigUpdated, object: nil, queue: nil) { (_) in
            self.refreshTransactionsList()
        }
```

И все, остальную обвязку с делегатом можно удалить.

2021-06-10 22:12 UTC, gregoryvit requested changes
Так лучше. Отписку можно удалить и можно сливать.

А в TokenService напиши TODO коммент, чтобы мы потом вернулись к этому сервису и зарефакторили. Сейчас он может легко уйти в неконсистентное состояние, но не вижу смысла на данном этапе править

2021-06-10 22:12 UTC, gregoryvit commented on zmoney/Controllers/TransactionsViewController.swift
> +
Не обязательно отписываться начиная с iOS 9.0. Так что можно убрать)

> If your app targets iOS 9.0 and later or macOS 10.11 and later, and you used addObserver(_:selector:name:object:), you do not need to unregister the observer. If you forget or are unable to remove the observer, the system cleans up the next time it would have posted to it.

https://developer.apple.com/documentation/foundation/notificationcenter/1413994-removeobserver

2021-06-11 06:33 UTC, merged